name: Test and Build Release

on:
  push:
    branches: [ main ]
jobs:
  test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: swift test
    
    - name: Build release
      run: swift build --configuration release
      
#     TODO dogfood changelog
