name: Swift

on:
  push:
    branches: [ main ]
jobs:
  test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: swift test
    
    - name: Build release
      run: swift build --configuration release
      
#     - name: Add to Changelog TODO dogfood changelog
