name: Test and Build Release

on:
  push:
    branches: [ main ]
jobs:
  build-release:
     runs-on: macos-latest
     steps:
       - run: swift build --configuration release
     
  test:
    needs: build-release
    runs-on: macos-latest
    steps:
    - name: Run tests
      run: swift test
